### ISSUE TITLE
[Bug] Blacklisting a user also allows the said user to bypass all filters

### ISSUE THREAD

**Issue by pixelomer** [Emy/janet#79] opened 2020-09-10 20:15 UTC
Blacklisting a user should only prevent the said user from using commands. However, instead of doing that, the bot completely ignores the said user. This allows the user to bypass all of the filters (word filter, spoiler filter, invite filter, etc.) without doing anything special.

**Comment by Emy** [comment] 2020-09-10 20:26
Correct we have observed this issue after you raised it. It is unintended behavior caused by using the already provided methods by the framework we use. We will try to look into the project as soon as possible. Thanks for the report.

**Comment by Emy** [comment] 2020-10-01 15:51
After some time we considered this to be the intended behaviour and therefore won't fix this.

**Closed by Emy** 2020-10-01 15:51 UTC
Labels: invalid, wontfix
